data<-read.table(pipe('grep "^[1-2]/2/2007" "household_power_consumption.txt"'),sep=";")
data1<-read.table("household_power_consumption.txt",header=T,sep=";")
names(data)<-names(data1)
with(data,plot(DT,Sub_metering_1,type="l",col="black"))
lines(data$DT,data$Sub_metering_2,type="l",col="red")
lines(data$DT,data$Sub_metering_3,type="l",col="blue")
legend("topright",lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png,"plot3.png")
dev.off()
