data<-read.table(pipe('grep "^[1-2]/2/2007" "household_power_consumption.txt"'),sep=";")
data1<-read.table("household_power_consumption.txt",header=T,sep=";")
names(data)<-names(data1)
data$Date<-as.Date(data$Date,format='%d/%m/%Y')
data$DT<-paste(data$Date,data$Time,sep="")
data$DT<-strptime(data$DT,format="%Y-%m-%d %H:%M:%S")
with(data,plot(DT,Global_active_power,type="l",xlab="",ylab="Global Active Power(kilowatts)"))
dev.copy(png,"plot2.png")
dev.off()
