data<-read.table(pipe('grep "^[1-2]/2/2007" "household_power_consumption.txt"'),sep=";")
data1<-read.table("household_power_consumption.txt",header=T,sep=";")
names(data)<-names(data1)
data$Date<-as.Date(data$Date,format='%d/%m/%Y')
data$DT<-paste(data$Date,data$Time,sep="")
data$DT<-strptime(data$DT,format="%Y-%m-%d %H:%M:%S")
par(mfrow=c(2,2))
with(data,{
           plot(DT,Global_active_power,type="l",xlab="",ylab="Global Active Power(kilowatts)")
          plot(DT,Voltage,type="l",xlab="datetime",ylab="Voltage")
          plot(DT,Sub_metering_1,type="l",col="black")
          lines(data$DT,data$Sub_metering_2,type="l",col="red")
          lines(data$DT,data$Sub_metering_3,type="l",col="blue")
          legend("topright",lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
          plot(DT,Global_reactive_power,type="l",xlab="datetime")
})
dev.copy(png,"plot4.png")
dev.off()
