data<-read.table(pipe('grep "^[1-2]/2/2007" "household_power_consumption.txt"'),sep=";")
data1<-read.table("household_power_consumption.txt",header=T,sep=";")
names(data)<-names(data1)
with(data,hist(Global_active_power,col="red",main="Global Active Power",xlab="Global Active Power(kilowatts)")) 
dev.copy(png,file="plot1.png")
dev.off()
